# golang:1.21.4 linux/amd64
FROM docker.io/library/golang@sha256:337543447173c2238c78d4851456760dcc57c1dfa8c3bcd94cbee8b0f7b32ad0 AS builder
FROM scratch

COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /etc/group /etc/group
COPY --from=builder /tmp /tmp
COPY --from=builder /dev /dev

ENV f2ray.location.asset=/opt/f2ray/share

COPY ./ /opt/f2ray/

ENTRYPOINT [ "/opt/f2ray/bin/f2ray" ]
CMD [ "run", "-config", "/etc/f2ray/config.json" ]
